### ISSUE TITLE
unable to understand (image_path)

### ISSUE THREAD

**Issue by aniiketdongare07** [danhdoan/computer-vision-raspberrypi#2]
`def app(image_path):`
`frm = cv.imread(image_path)`
`def main(args):
    app(args.image)`

I'm having issues with the image_path, I'm new to Python and I keep getting this error :

*Traceback (most recent call last):
 File "app-emotion-image.py", line 50, in <module>
   main(download.jpeg)
NameError: name 'download' is not defined*

Also, in `def main(args)`, what exactly would be "args"?

Any help would be appreciated, I'm trying to run 008-pi-emotion-recognition over my Raspberry Pi.

**Comment by Safename321** [comment]
Setup anydesk or take a video of the error

Sent from Mail for Windows 10

From: aniiketdongare07
Sent: Sunday, March 22, 2020 11:08 AM
To: danhdoan/computer-vision-raspberrypi
Cc: Subscribed
Subject: [danhdoan/computer-vision-raspberrypi] unable to understand(image_path) (#2)

def app(image_path):
frm = cv.imread(image_path)
def main(args): app(args.image)
I'm having issues with the image_path, I'm new to Python and I keep getting this error :
Traceback (most recent call last):
File "app-emotion-image.py", line 50, in 
main(download.jpeg)
NameError: name 'download' is not defined
Any help would be appreciated, I'm trying to run 008-pi-emotion-recognition over my Raspberry Pi.

**Comment by aniiketdongare07** [comment]
@Safename321 
![errorgit](https://user-images.githubusercontent.com/43856168/77253428-21637000-6c80-11ea-87f2-47d6f2a61d50.jpeg)


This is the image I can share at the moment

**Comment by danhdoan** [comment]
Hi aniiketdongare07,

Your command to run this sample is incorrect, try the one below:
python app-emotion-image.py -i /path/to/image

Check for more detail at Usage - section 3 [[link]](https://github.com/danhdoan/computer-vision-raspberrypi#usage)

**Comment by aniiketdongare07** [comment]
@danhdoan Thank you, I'll try this right away :)

**Comment by aniiketdongare07** [comment]
@danhdoan I tried running the command you told me to run and found myself seeing this error : 


`python app-emotion-image.py -i /home/pi/MagicMirror/modules/workspace/computer-vision-raspberrypi/008-pi-emotion-recognition/download.jpeg
2020-03-22 21:08:30,429  [INFO]  Raspberry Pi: Emotion Recognition

Traceback (most recent call last):
 File "app-emotion-image.py", line 50, in <module>
   main(args)
 File "app-emotion-image.py", line 43, in main
   app(args.image)
 File "app-emotion-image.py", line 18, in app
   face_detector = FaceDetector()
 File "/home/pi/MagicMirror/modules/workspace/computer-vision-raspberrypi/008-pi-emotion-recognition/altusi/facedetector.py", line 22, in __init__
   self.__net = cv.dnn.readNet(xml_path, bin_path)
cv2.error: OpenCV(4.1.0) /home/x/opencv_all/opencv-4.1.0/modules/dnn/src/dnn.cpp:2670: error: (-2:Unspecified error) Build OpenCV with Inference Engine to enable loading models from Model Optimizer. in function 'readFromModelOptimizer'`

**Comment by danhdoan** [comment]
Turn out you just need to install OpenVINO instead of the original OpenCV. Follow my installation guide to setup.

**Comment by aniiketdongare07** [comment]
@danhdoan I'll check out your git

**Comment by Safename321** [comment]
Thanks 

Sent from Mail for Windows 10
